### PR TITLE
add pkg.files to ignore file when npm publish

### PR DESCRIPTION
**Pull request by popomore**

### CODE REVIEW

**Comment by popomore** [comment]
before

```
PKGFILES SUMMARY
Size on Disk with Dependencies  ~626.69 kB
Size with Dependencies          ~485.07 kB
Publishable Size                ~163.67 kB
Number of Directories           4         
Number of Files                 32  
```

after

```
PKGFILES SUMMARY
Size on Disk with Dependencies  ~626.69 kB
Size with Dependencies          ~485.11 kB
Publishable Size                ~51.86 kB 
Number of Directories           2         
Number of Files                 14    
```

**Comment by popomore** [comment]
@othiym23 ping

**Comment by popomore** [comment]
ping

**Comment by popomore** [comment]
Any response?

**Comment by popomore** [comment]
???

**Comment by isaacs** [comment]
Done on v3.

**Pull request closed without merging**
