### PR TITLE
bugfix: address "write after end" bug

### PR DESCRIPTION
**Pull request by stsvilik**
#180

### CODE REVIEW

**Comment by prabhu** [comment]
Any chance of fixing this defect?

**Comment by stsvilik** [comment]
@prabhu The underlying defect is already addressed here https://github.com/isaacs/minipass/commit/55ed167abda3f2efb0ab900b7e080675b101e083, however this PR is valid as well and further enhances reliability

**Comment by isaacs** [comment]
I'd rather not use `.once()` if the event can only be emitted once anyway.

The `write after end` issue was not actually related to multiple `end` events being emitted, but rather to pacote _actually writing after end_, because it was writing to a stream that was already being piped into.

**Comment by stsvilik** [comment]
My thought was that using `.once()` would simply reinforce the rule in case some code attempts (mistakenly) invoke `end` second time. I agree that it might masque the real problem, but at least it wouldn't break (like it did).

**Comment by captainkovalsky** [comment]
This bug is reproduced on mac os. It's really awkful

**Comment by shibinrajumathew** [comment]
This bug is reproduced on ubunt also

**Pull request closed without merging**
