### PR TITLE
Drop mkdirp package

### PR DESCRIPTION
**Pull request by Umoxfo**
# What / Why
Since Node.js v10.0.0, the recursive directory creation has been supported.

### CODE REVIEW

**Comment by isaacs** [comment]
It would be better to upgrade to mkdirp 1.0, which uses the native implementation if available, but still maintains the same semantics as mkdirp 0.x (returning the first made directory, handling errors properly on Windows, etc.)

**Comment by ruyadorno** [comment]
> returning the first made directory

oh btw @isaacs it has come to my attention that Ben implemented this bit: https://github.com/nodejs/node/commit/13fe56bbbbc290cbc16804994ce0ec1d25729775 (not sure if it was backported or only available on latest nodejs tho)

**Comment by coreyfarrell** [comment]
`fs.promises` prints an experimental warning in 10.13.0 (first LTS of the 10.x line).  Since this package advertises 10.x support I think it should not use fs.promises for this reason.  Also fs.mkdir did not support recursive at all until 10.12.0 - not sure if non-LTS 10.x versions currently work with `tar` but this seems like a potentially breaking change.

@ruyadorno Recursive fs.mkdir returns the first created directory in 13.11.0+.  I do not believe it has been backported to 10.x or 12.x (yet anyways).

@dctheobald the fix for the minimist vulnerability was backported to mkdirp@0.5.x so you only need to update your own repository, `npm i tar` on a fresh repository does not produce any audit notices.

**Comment by isaacs** [comment]
This module is using the latest and greatest mkdirp, which uses the builtin if available and trustworthy.  Closing.

**Pull request closed without merging**
